const path = require('path');

// This file is the entry point for Passenger on shared hosting.
// It points to the standalone build generated by Next.js.

process.env.NODE_ENV = 'production';
process.chdir(__dirname);

const { startServer } = require('./.next/standalone/server.js');

// Passenger automatically handles the port, but we can set defaults if needed.
const port = process.env.PORT || 3000;
const hostname = 'localhost';

console.log(`Starting production server on ${hostname}:${port}`);
